[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.build]
cmds = [
    "cd backend",
    "pip install -r requirements.txt"
]

[phases.deploy]
cmds = [
    "cd backend",
    "python run.py"
]

[start]
cmd = "cd backend && python run.py"
