# Nixpacks configuration for Railway deployment

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p uploaded_docs", "mkdir -p chroma_db"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
